### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by serieznyi** [coreyworrell/Kohana-Assets#6]
How about add license file to your project? For example MIT license.

**Comment by coreyworrell** [comment]
What would be the reasoning for including a license?

**Comment by serieznyi** [comment]
Because I need know what i may do with your code and this is a good practice. This is important!

**Comment by coreyworrell** [comment]
There's no license so you can do whatever you want with it. Thank you for checking first though.

**Comment by serieznyi** [comment]
License absence not guaranteed what I may do with your product anything. Sorry, but i need protect themselves. What you think if I myself add license file and create pull request? I think this is may be MIT or BSD license. The difference in them is not a big.

**Comment by coreyworrell** [comment]
Closed by #7
